plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Joke's Blog
author: 
  name : jomosko
description: > #
  A short synopsis of my tech and science exporations.
show_excerpts: false # 

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:

    - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/fourieroptics" }
    - { platform: keybase,        user_url: "https://keybase.io/jekyll" }


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - projects.md
 - papers.md
 
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
